version: '3'

services:
  wp:
    build: .
    container_name: "${PREFIX}_wp"
    restart: "always"
    user: root
    ports:
      - ${IP}:80:80
    volumes:
      - ${BUILDER_DIR}/config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ${PROJECT_DIR}/wp:/var/www/html
      - ${PROJECT_DIR}/logs:/var/log/apache2
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress_data
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: "${PREFIX}_mysql"
    user: root
    restart: "always"
    ports:
      - ${IP}:3306:3306
    command: [
      '--default_authentication_plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ${PROJECT_DIR}/database/dump:/docker-entrypoint-initdb.d
      - ${PROJECT_DIR}/database/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress_data
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10