version: '3'

services:
  wp:
    image: wordpress:${WP_VERSION}
    container_name: "${PREFIX}_wp"
    restart: "always"
    user: root
    ports:
      - ${IP}:80:80
    volumes:
      - ./config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./site/wp:/var/www/html
      - ./logs:/var/log/apache2
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress_data
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - db
      - gulp


  wpcli:
    image: wordpress:cli
    container_name: "${PREFIX}_wpcli"
    restart: "on-failure"
    user: root
    depends_on:
      - db
      - wp
      - gulp
    volumes:
      - ./site/wp:/var/www/html
    entrypoint: wp
    command: "--info"


  gulp:
    image: node:latest
    container_name: "${PREFIX}_gulp"
    restart: "on-failure"
    user: root
    working_dir: /home/node/app/wp-content/themes/${SLUG}
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./site/wp:/home/node/app


  db:
    image: mysql:8
    container_name: "${PREFIX}_mysql"
    user: root
    restart: "always"
    ports:
      - ${IP}:3306:3306
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./site/database/dump:/docker-entrypoint-initdb.d
      - ./site/database/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress_data
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10


  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: "${PREFIX}_phpmyadmin"
      depends_on:
          - db
      ports:
          - ${IP}:8000:80
      environment:
          MYSQL_USER: root
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password