version: '3'

services:
  wpcli:
    image: wordpress:${WP_VERSION}
    container_name: "${PREFIX}_wpcli"
    restart: "always"
    user: root
    ports:
      - ${IP}:80:80
    volumes:
      - ${BUILDER_DIR}/config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ${BUILDER_DIR}/config/wp-cli-install.sh:/bin/wp-cli-install.sh
      - ${PROJECT_DIR}/wp:/var/www/html
      - ${PROJECT_DIR}/logs:/var/log/apache2
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress_data
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_TABLE_PREFIX: ${DB_PREFIX}
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: "${PREFIX}_mysql"
    user: root
    restart: "always"
    ports:
      - ${IP}:3306:3306
    command: [
      '--default_authentication_plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ${PROJECT_DIR}/database/dump:/docker-entrypoint-initdb.d
      - ${PROJECT_DIR}/database/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress_data
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${PREFIX}_phpmyadmin"
    restart: "no"
    depends_on:
        - db
    ports:
        - ${IP}:8000:80
    environment:
        MYSQL_USER: root
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password